//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAgendaCultural {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosSQL() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoAgendaCultural.RecursosSQL", typeof(RecursosSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USE AgendaCulturalDB;  
        ///GO  
        ///CREATE PROCEDURE [AgendaCulturalDB].[sp_ListarEventosIndex] 
        ///AS   
        ///    SET NOCOUNT ON;  
        ///    SELECT TOP(9) ev.Id as Id_evento,ev.Imagen,ev.Nombre as Nombre_evento,ev.Descripcion,ct.Id, ct.Nombre as Categoria
        ///	,lg.Id as Id_lugar,lg.Nombre as Nombre_lugar,cl.Fecha as Fecha_evento
        ///    FROM AgendaCulturalDB.Evento ev
        ///	INNER JOIN AgendaCulturalDB.Categoria ct
        ///	ON ct.Id=ev.CategoriaId
        ///	INNER JOIN AgendaCulturalDB.Lugar lg
        ///	ON ev.LugarId=lg.Id
        ///	INNER JOIN AgendaCulturalDB.C [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Listar_sp_Index_Eventos {
            get {
                return ResourceManager.GetString("Listar_sp_Index_Eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USE AgendaCulturalDB;  
        ///GO  
        ///CREATE PROCEDURE [AgendaCulturalDB].[sp_ListarEventos] 
        ///AS   
        ///
        ///    SET NOCOUNT ON;  
        ///    SELECT ev.Id as Id_evento,ev.Imagen,ev.Nombre as Nombre_evento,ev.Descripcion,ct.Id, ct.Nombre as Categoria
        ///	,lg.Id as Id_lugar,lg.Nombre as Nombre_lugar,cl.Fecha as Fecha_evento
        ///    FROM AgendaCulturalDB.Evento ev
        ///	INNER JOIN AgendaCulturalDB.Categoria ct
        ///	ON ct.Id=ev.CategoriaId
        ///	INNER JOIN AgendaCulturalDB.Lugar lg
        ///	ON ev.LugarId=lg.Id
        ///	INNER JOIN AgendaCulturalDB.Calendario  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Listar_sp_Todos_Eventos {
            get {
                return ResourceManager.GetString("Listar_sp_Todos_Eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [AgendaCulturalDB].[sp_ListarEventos].
        /// </summary>
        internal static string sp_ListarEventos {
            get {
                return ResourceManager.GetString("sp_ListarEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [AgendaCulturalDB].[sp_ListarEventosIndex].
        /// </summary>
        internal static string sp_ListarEventosIndex {
            get {
                return ResourceManager.GetString("sp_ListarEventosIndex", resourceCulture);
            }
        }
    }
}
